// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjwlNYbKoob8Aedc6rGbdVa5uHTW6Jp_o',
    appId: '1:217380092811:web:8bccb64766c83ff47d8d8e',
    messagingSenderId: '217380092811',
    projectId: 'flow-chat-42595',
    authDomain: 'flow-chat-42595.firebaseapp.com',
    storageBucket: 'flow-chat-42595.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBN93Ia7yIYNshMZ-6QySKroYqAFH_buTo',
    appId: '1:217380092811:android:e7db0e09d8c0279f7d8d8e',
    messagingSenderId: '217380092811',
    projectId: 'flow-chat-42595',
    storageBucket: 'flow-chat-42595.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuf0CkEUZ1RcH0q4sOjEfq2GKYnYH74NA',
    appId: '1:217380092811:ios:306a82d4e7c41c4f7d8d8e',
    messagingSenderId: '217380092811',
    projectId: 'flow-chat-42595',
    storageBucket: 'flow-chat-42595.appspot.com',
    androidClientId: '217380092811-ddc1ner7k6f24nqpvc80sepg4ga7kqjs.apps.googleusercontent.com',
    iosClientId: '217380092811-ofgm4gqk2bg86srt2955lraeb9f8bi6k.apps.googleusercontent.com',
    iosBundleId: 'com.example.flowchat',
  );
}
